export { requireAdmin, type Ctx, type UserRole } from "./context";
export { CoreError, notFound, forbidden, invalid } from "./errors";
export { hashPassword, normalizeEmail } from "./accounts";
export * from "./contract";
export * as projectsService from "./projects";
export type { ProjectListItem, ProjectDetail } from "./projects";
export * as projectClientService from "./project-client";
export * as usersService from "./users";
export type { UserListItem } from "./users";
export * as clientsService from "./clients";
export * as documentsService from "./documents";
export * as photosService from "./photos";
export { canManageProjectFiles, type StoredFile } from "./project-files";
export * as clientAccountService from "./client-account";
